import { PrismaClient } from '@prisma/client'

const db = new PrismaClient()

const categories = [
  { name: 'Furniture', slug: 'furniture', icon: '🛋️', featured: true, sortOrder: 1, description: 'Sofas, chairs, tables, beds and storage.' },
  { name: 'Lighting', slug: 'lighting', icon: '💡', featured: true, sortOrder: 2, description: 'Pendants, floor lamps, sconces and chandeliers.' },
  { name: 'Wall Art & Decor', slug: 'wall-art-decor', icon: '🖼️', featured: true, sortOrder: 3, description: 'Prints, mirrors, panels and wall sculptures.' },
  { name: 'Textiles & Soft Furnishings', slug: 'textiles', icon: '🧶', featured: true, sortOrder: 4, description: 'Rugs, curtains, cushions, throws and bedding.' },
  { name: 'Kitchen & Dining', slug: 'kitchen-dining', icon: '🍽️', featured: false, sortOrder: 5, description: 'Tableware, cookware and kitchen decor.' },
  { name: 'Bathroom', slug: 'bathroom', icon: '🚿', featured: false, sortOrder: 6, description: 'Fixtures, accessories and bath textiles.' },
  { name: 'Outdoor Living', slug: 'outdoor-living', icon: '🌿', featured: true, sortOrder: 7, description: 'Patio furniture, planters and garden decor.' },
  { name: 'Storage & Organisation', slug: 'storage-organisation', icon: '📦', featured: false, sortOrder: 8, description: 'Shelving, baskets and organisers.' },
  { name: 'Plants & Botanicals', slug: 'plants-botanicals', icon: '🌱', featured: false, sortOrder: 9, description: 'Planters, terrariums and botanical decor.' },
  { name: 'Art & Sculptures', slug: 'art-sculptures', icon: '🗿', featured: false, sortOrder: 10, description: 'Sculptures, ceramics and art objects.' },
  { name: 'Flooring & Tiles', slug: 'flooring-tiles', icon: '🏠', featured: false, sortOrder: 11, description: 'Hardwood, tiles, luxury vinyl and carpet.' },
  { name: 'Smart Home', slug: 'smart-home', icon: '📱', featured: false, sortOrder: 12, description: 'Smart lighting, thermostats and automation.' },
  { name: 'Paint & Wallcoverings', slug: 'paint-wallcoverings', icon: '🎨', featured: false, sortOrder: 13, description: 'Premium paints, wallpapers and specialty finishes.' },
  { name: 'Architectural Elements', slug: 'architectural-elements', icon: '🏛️', featured: false, sortOrder: 14, description: 'Doors, trim, fireplace surrounds and moulding.' },
]

const products = [
  // FURNITURE
  { name: 'Arc Modular Sofa — Terracotta', slug: 'arc-modular-sofa-terracotta', categorySlug: 'furniture', price: 3200, comparePrice: 3900, featured: true, newArrival: true, bestSeller: false, stock: 8, material: 'Bouclé fabric, solid walnut legs', dimensions: 'W280 × D95 × H75 cm', origin: 'Italy', shortDesc: 'A sculptural modular sofa in warm bouclé. Configure it your way.', description: 'The Arc Modular Sofa redefines living room comfort through bold geometry and artisan craft. Its sweeping curved form is upholstered in premium Italian bouclé with solid walnut legs that ground the design. Fully modular — build the configuration your space demands.', tags: ['sofa', 'modular', 'living room', 'minimal'], images: ['https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80', 'https://images.unsplash.com/photo-1567016432779-094069958ea5?w=800&q=80'] },
  { name: 'Slab Dining Table — White Marble', slug: 'slab-dining-table-marble', categorySlug: 'furniture', price: 4800, comparePrice: null, featured: true, newArrival: false, bestSeller: true, stock: 5, material: 'Carrara marble, blackened steel base', dimensions: 'W220 × D95 × H75 cm', origin: 'Portugal', shortDesc: 'A single slab of Carrara marble on a minimal blackened steel frame.', description: 'The Slab Dining Table is a statement of restraint and luxury. Each top is cut from a single slab of Carrara marble, showcasing natural veining unique to each piece. The blackened steel hairpin base provides structural contrast.', tags: ['dining table', 'marble', 'dining room'], images: ['https://images.unsplash.com/photo-1617104678098-de229db51175?w=800&q=80', 'https://images.unsplash.com/photo-1604578762246-41134e37f9cc?w=800&q=80'] },
  { name: 'Void Lounge Chair — Charcoal', slug: 'void-lounge-chair-charcoal', categorySlug: 'furniture', price: 1450, comparePrice: 1750, featured: true, newArrival: false, bestSeller: true, stock: 12, material: 'Wool blend, powder-coated steel', dimensions: 'W70 × D80 × H85 cm', origin: 'Denmark', shortDesc: 'A sculptural lounge chair inspired by the geometry of negative space.', description: 'The Void Lounge Chair draws from Scandinavian design tradition while pushing into contemporary avant-garde territory. Its curved shell is upholstered in a dense wool blend, supported by a precision powder-coated steel frame.', tags: ['chair', 'lounge', 'living room', 'scandinavian'], images: ['https://images.unsplash.com/photo-1567016376408-0226e4d0c1ea?w=800&q=80'] },
  { name: 'Form Bed Frame — Smoked Oak', slug: 'form-bed-frame-smoked-oak', categorySlug: 'furniture', price: 2200, comparePrice: null, featured: false, newArrival: true, bestSeller: false, stock: 6, material: 'Smoked solid oak', dimensions: 'W180 × D210 × H90 cm (King)', origin: 'Japan', shortDesc: 'A low-profile bed frame in smoked solid oak. Simple. Permanent.', description: 'The Form Bed Frame embodies the Japanese principle of ma — the beauty of empty space. Its low profile and clean slab construction in smoked solid oak creates a serene foundation for sleep.', tags: ['bed', 'bedroom', 'oak', 'japanese', 'minimal'], images: ['https://images.unsplash.com/photo-1617325247661-675ab4b64ae2?w=800&q=80'] },
  { name: 'Column Bookshelf — Brass & Black', slug: 'column-bookshelf-brass-black', categorySlug: 'furniture', price: 980, comparePrice: null, featured: false, newArrival: false, bestSeller: true, stock: 15, material: 'Powder-coated steel, brass accents', dimensions: 'W80 × D35 × H200 cm', origin: 'Germany', shortDesc: 'Architectural shelving with brass accent joints.', description: 'The Column Bookshelf bridges industrial rigour with refined materiality. Matte-black powder-coated steel uprights connect through polished brass fittings to create a display piece as beautiful as what it holds.', tags: ['bookshelf', 'storage', 'living room', 'study'], images: ['https://images.unsplash.com/photo-1594026112284-02bb6f3352fe?w=800&q=80'] },

  // LIGHTING
  { name: 'Orbit Pendant — Brushed Brass', slug: 'orbit-pendant-brushed-brass', categorySlug: 'lighting', price: 680, comparePrice: null, featured: true, newArrival: true, bestSeller: false, stock: 20, material: 'Brushed brass, hand-blown glass', dimensions: 'Ø40 cm, drop adjustable to 150 cm', origin: 'Sweden', shortDesc: 'A hand-blown glass globe suspended in brushed brass armature.', description: 'The Orbit Pendant is designed around the tension between transparency and mass. Each globe is individually hand-blown, creating subtle variations in glass texture that catch and diffuse light beautifully.', tags: ['pendant', 'lighting', 'dining', 'brass', 'glass'], images: ['https://images.unsplash.com/photo-1565814636199-ae8133055c1c?w=800&q=80'] },
  { name: 'Mono Floor Lamp — Matte Black', slug: 'mono-floor-lamp-matte-black', categorySlug: 'lighting', price: 420, comparePrice: 520, featured: true, newArrival: false, bestSeller: true, stock: 18, material: 'Powder-coated steel, linen shade', dimensions: 'Base Ø30 cm, height 155 cm', origin: 'Netherlands', shortDesc: 'An architectural floor lamp with a pivoting linen shade.', description: 'The Mono Floor Lamp strips lighting down to its essential geometry. A single matte-black stem rises to a pivoting linen shade, allowing precise directional light. The weighted concrete base ensures stability.', tags: ['floor lamp', 'lighting', 'living room', 'minimal'], images: ['https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&q=80'] },
  { name: 'Grid Wall Sconce — Antique Brass', slug: 'grid-wall-sconce-antique-brass', categorySlug: 'lighting', price: 310, comparePrice: null, featured: false, newArrival: true, bestSeller: false, stock: 25, material: 'Antique brass, frosted glass', dimensions: 'W15 × D20 × H25 cm', origin: 'France', shortDesc: 'A geometric wall sconce that casts dramatic shadow patterns.', description: 'The Grid Wall Sconce projects intricate geometric light patterns across walls and ceilings, transforming any surface into living texture. The frosted glass diffuses the light source while the antique brass cage creates the pattern.', tags: ['sconce', 'wall light', 'bedroom', 'brass'], images: ['https://images.unsplash.com/photo-1540932239986-30128078f3c5?w=800&q=80'] },
  { name: 'Cascade Chandelier — Smoked Glass', slug: 'cascade-chandelier-smoked-glass', categorySlug: 'lighting', price: 1850, comparePrice: 2200, featured: true, newArrival: false, bestSeller: false, stock: 4, material: 'Smoked hand-blown glass, satin nickel', dimensions: 'Ø65 cm, drop 80–180 cm', origin: 'Czech Republic', shortDesc: 'A cascading arrangement of smoked glass spheres.', description: 'The Cascade Chandelier arranges twelve individually hand-blown smoked glass spheres on satin nickel stems at varying heights, creating a dramatic focal point for dining rooms and entryways.', tags: ['chandelier', 'dining', 'statement', 'glass'], images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80'] },

  // WALL ART & DECOR
  { name: 'Abstract Composition No. 7', slug: 'abstract-composition-no-7', categorySlug: 'wall-art-decor', price: 1200, comparePrice: null, featured: true, newArrival: true, bestSeller: false, stock: 3, material: 'Oil on linen, natural wood frame', dimensions: '100 × 140 cm', origin: 'Spain', shortDesc: 'Original oil painting — warm earth tones on linen.', description: 'Abstract Composition No. 7 is an original painting by Barcelona-based artist Clara Montserrat. Layered earth pigments and raw linen create a surface that shifts with the light throughout the day. Each piece is unique.', tags: ['art', 'painting', 'original', 'abstract'], images: ['https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=800&q=80'] },
  { name: 'Arch Mirror — Antiqued Bronze', slug: 'arch-mirror-antiqued-bronze', categorySlug: 'wall-art-decor', price: 890, comparePrice: 1050, featured: true, newArrival: false, bestSeller: true, stock: 10, material: 'Antiqued bronze frame, bevelled glass', dimensions: 'W60 × H140 cm', origin: 'Italy', shortDesc: 'A full-length arch mirror with an antiqued bronze frame.', description: 'Modelled on classical European arch forms, this mirror combines antiqued bronze casting with hand-bevelled glass. It stands as both functional dressing mirror and wall sculpture.', tags: ['mirror', 'entryway', 'bedroom', 'arch'], images: ['https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800&q=80'] },
  { name: 'Woven Wall Panel — Natural Jute', slug: 'woven-wall-panel-natural-jute', categorySlug: 'wall-art-decor', price: 340, comparePrice: null, featured: false, newArrival: true, bestSeller: false, stock: 14, material: 'Natural jute, cotton warp', dimensions: 'W80 × H120 cm', origin: 'Morocco', shortDesc: 'A handwoven jute wall panel with organic texture.', description: 'Hand-woven by artisans in Marrakech using traditional techniques, this jute wall panel brings warmth and organic texture to any room. No two pieces are identical.', tags: ['wall art', 'textile', 'woven', 'natural'], images: ['https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80'] },

  // TEXTILES
  { name: 'Stone Linen Duvet Cover — King', slug: 'stone-linen-duvet-cover-king', categorySlug: 'textiles', price: 280, comparePrice: null, featured: false, newArrival: false, bestSeller: true, stock: 30, material: '100% stonewashed French linen', dimensions: 'W230 × H220 cm', origin: 'France', shortDesc: 'Stonewashed French linen. Pre-washed for softness from day one.', description: 'Grown and woven in Normandy, France, this linen becomes softer with each wash. The stonewash process gives it a relaxed, lived-in texture that improves over time. OEKO-TEX certified.', tags: ['bedding', 'linen', 'bedroom', 'sleep'], images: ['https://images.unsplash.com/photo-1631679706909-1844bbd07221?w=800&q=80'] },
  { name: 'Geometric Wool Rug — 200×300 cm', slug: 'geometric-wool-rug-200x300', categorySlug: 'textiles', price: 960, comparePrice: 1150, featured: true, newArrival: true, bestSeller: false, stock: 7, material: 'Hand-knotted New Zealand wool', dimensions: '200 × 300 cm', origin: 'Nepal', shortDesc: 'Hand-knotted geometric rug in a muted avant-garde palette.', description: 'Each rug is hand-knotted by master weavers in Kathmandu using New Zealand wool yarn dyed with low-impact dyes. The bold geometric pattern draws from Berber and Bauhaus traditions.', tags: ['rug', 'living room', 'bedroom', 'geometric', 'wool'], images: ['https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=800&q=80'] },
  { name: 'Chunky Knit Throw — Ivory', slug: 'chunky-knit-throw-ivory', categorySlug: 'textiles', price: 195, comparePrice: null, featured: false, newArrival: false, bestSeller: true, stock: 40, material: 'Merino wool blend', dimensions: 'W130 × H170 cm', origin: 'Scotland', shortDesc: 'A generously oversized chunky-knit throw in ivory merino.', description: 'Knitted on heritage looms in the Scottish Borders, this throw wraps you in substantial warmth without weight. The open-weave pattern allows it to drape naturally across sofas and beds.', tags: ['throw', 'bedroom', 'sofa', 'cosy', 'wool'], images: ['https://images.unsplash.com/photo-1540638349517-3abd5afc5847?w=800&q=80'] },

  // KITCHEN & DINING
  { name: 'Matte Black Dinnerware Set — 12pc', slug: 'matte-black-dinnerware-set-12pc', categorySlug: 'kitchen-dining', price: 340, comparePrice: null, featured: false, newArrival: true, bestSeller: false, stock: 20, material: 'Stoneware with matte black reactive glaze', dimensions: 'Dinner plate Ø27 cm', origin: 'Japan', shortDesc: 'Reactive-glaze stoneware with a subtle matte-black finish.', description: 'Each piece in this 12-piece set is individually kiln-fired using a reactive glaze technique, producing unique surface variations of deep matte black. Includes 4 dinner plates, 4 bowls, 4 side plates.', tags: ['dinnerware', 'kitchen', 'dining', 'stoneware', 'black'], images: ['https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80'] },
  { name: 'Hammered Brass Candle Holders — Set of 3', slug: 'hammered-brass-candle-holders-set-3', categorySlug: 'kitchen-dining', price: 145, comparePrice: 175, featured: false, newArrival: false, bestSeller: true, stock: 35, material: 'Hand-hammered solid brass', dimensions: 'Heights: 8, 14, 20 cm', origin: 'India', shortDesc: 'Hand-hammered solid brass candle holders in three heights.', description: 'Crafted by artisans using traditional hammering techniques, these three brass candle holders create a dynamic table centrepiece. The hammered surface catches candlelight and creates a warm ambient glow.', tags: ['candle holders', 'dining', 'brass', 'decor'], images: ['https://images.unsplash.com/photo-1543512214-318c7553f230?w=800&q=80'] },

  // OUTDOOR LIVING
  { name: 'Teak Lounge Chair — Outdoor', slug: 'teak-lounge-chair-outdoor', categorySlug: 'outdoor-living', price: 1100, comparePrice: null, featured: true, newArrival: false, bestSeller: false, stock: 9, material: 'FSC-certified teak, Sunbrella cushion', dimensions: 'W70 × D150 × H85 cm', origin: 'Indonesia', shortDesc: 'FSC-certified teak lounger with Sunbrella cushions.', description: 'Crafted from sustainably sourced FSC-certified teak, this lounger develops a beautiful silver-grey patina over time or can be oiled to maintain its golden warmth. The cushion uses Sunbrella fabric for UV and mildew resistance.', tags: ['outdoor', 'lounge chair', 'teak', 'garden', 'patio'], images: ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80'] },
  { name: 'Terrazzo Plant Pot — Large', slug: 'terrazzo-plant-pot-large', categorySlug: 'outdoor-living', price: 185, comparePrice: null, featured: false, newArrival: true, bestSeller: false, stock: 22, material: 'Hand-cast terrazzo', dimensions: 'Ø45 × H50 cm', origin: 'Portugal', shortDesc: 'Hand-cast terrazzo pot with visible stone aggregate.', description: 'Each pot is individually hand-cast in Lisbon using a blend of marble aggregate and white Portland cement. Drainage hole included. Suitable for indoor and outdoor use.', tags: ['planter', 'outdoor', 'terrazzo', 'plants'], images: ['https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&q=80'] },

  // ART & SCULPTURES
  { name: 'Void Ceramic Sculpture', slug: 'void-ceramic-sculpture', categorySlug: 'art-sculptures', price: 640, comparePrice: null, featured: true, newArrival: true, bestSeller: false, stock: 6, material: 'Hand-thrown stoneware, tenmoku glaze', dimensions: 'W25 × H35 cm', origin: 'United Kingdom', shortDesc: 'A hand-thrown stoneware vessel with tenmoku glaze.', description: 'Thrown and finished by London ceramicist James Alderton, each Void sculpture is a unique exploration of form and negative space. The tenmoku glaze creates an iridescent dark surface.', tags: ['sculpture', 'ceramic', 'art', 'decorative'], images: ['https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=800&q=80'] },

  // BATHROOM
  { name: 'Concrete Basin — Oval', slug: 'concrete-basin-oval', categorySlug: 'bathroom', price: 780, comparePrice: null, featured: false, newArrival: false, bestSeller: false, stock: 10, material: 'GFRC concrete, sealed finish', dimensions: 'W60 × D40 × H15 cm', origin: 'Australia', shortDesc: 'A cast concrete countertop basin with sealed matte finish.', description: 'Cast from glass-fibre reinforced concrete (GFRC) to achieve a thin-wall profile that belies the material\'s strength. Each basin is sealed with a penetrating sealer for water resistance and easy cleaning.', tags: ['bathroom', 'basin', 'concrete', 'renovation'], images: ['https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800&q=80'] },

  // SMART HOME
  { name: 'Smart Dimmer Switch — Brushed Nickel', slug: 'smart-dimmer-switch-brushed-nickel', categorySlug: 'smart-home', price: 89, comparePrice: null, featured: false, newArrival: true, bestSeller: false, stock: 50, material: 'Brushed nickel face plate, WiFi module', dimensions: 'Standard single gang', origin: 'USA', shortDesc: 'WiFi-enabled smart dimmer. Works with Alexa, Google & HomeKit.', description: 'Replace your standard switch with this smart dimmer to gain app control, scheduling, scenes, and voice control through Alexa, Google Assistant, and Apple HomeKit. The brushed nickel face plate is designed to complement premium interiors.', tags: ['smart home', 'lighting', 'dimmer', 'wifi'], images: ['https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800&q=80'] },

  // PLANTS & BOTANICALS
  { name: 'Hanging Terrarium — Geometric', slug: 'hanging-terrarium-geometric', categorySlug: 'plants-botanicals', price: 95, comparePrice: 115, featured: false, newArrival: false, bestSeller: true, stock: 30, material: 'Powder-coated steel, tempered glass', dimensions: 'Ø20 cm, rope drop 60 cm', origin: 'Germany', shortDesc: 'A geometric hanging terrarium for air plants and moss.', description: 'This twelve-faceted geometric terrarium is powder-coated in matte black steel with open sides for air circulation. Perfect for air plants, preserved moss, or small succulents.', tags: ['plants', 'terrarium', 'hanging', 'geometric', 'botanical'], images: ['https://images.unsplash.com/photo-1463320726281-696a485928c7?w=800&q=80'] },

  // FLOORING
  { name: 'Zellige Terracotta Tiles — m²', slug: 'zellige-terracotta-tiles-sqm', categorySlug: 'flooring-tiles', price: 95, comparePrice: null, featured: false, newArrival: true, bestSeller: false, stock: 200, material: 'Hand-cut zellige ceramic', dimensions: '10×10 cm tiles, sold per m²', origin: 'Morocco', shortDesc: 'Handmade zellige tiles with characteristic surface variation.', description: 'Cut and glazed by hand in Fez, Morocco, these terracotta zellige tiles display the intentional imperfection that defines the craft. No two tiles are identical. Suitable for floors, walls, and splashbacks.', tags: ['tiles', 'flooring', 'kitchen', 'bathroom', 'moroccan'], images: ['https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800&q=80'] },

  // PAINT & WALLCOVERINGS
  { name: 'Chalk Paint — Warm Stone (2.5L)', slug: 'chalk-paint-warm-stone-2-5l', categorySlug: 'paint-wallcoverings', price: 68, comparePrice: null, featured: false, newArrival: false, bestSeller: true, stock: 80, material: 'Zero-VOC chalk-based paint', dimensions: '2.5L (covers approx. 20 m²)', origin: 'UK', shortDesc: 'A zero-VOC chalk paint in the signature Warm Stone tone.', description: 'Warm Stone is Maison Avant-Garde\'s signature neutral — a nuanced stone that shifts from warm grey to pale sand depending on the light. Zero-VOC formula. Water-based, low-odour, and wipeable when sealed.', tags: ['paint', 'wall', 'renovation', 'neutral'], images: ['https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=800&q=80'] },
]

const services = [
  { name: 'Interior Design Consultation', slug: 'interior-design-consultation', price: 150, priceType: 'HOURLY' as const, duration: '1–3 hours', featured: true, sortOrder: 1, shortDesc: 'One-on-one session with our lead designers to define your vision.', description: 'Work directly with one of our lead interior designers to develop a clear vision for your space. We review your existing layout, discuss your aesthetic goals, explore material and colour options, and create a prioritised action plan. Available in-person or via video call.' },
  { name: 'Full Room Makeover', slug: 'full-room-makeover', price: 2500, priceType: 'FIXED' as const, duration: '2–3 weeks', featured: true, sortOrder: 2, shortDesc: 'Complete transformation — furniture, art, lighting and styling.', description: 'A comprehensive room transformation handled from first concept to final styling. Includes design planning, product sourcing, delivery coordination, installation, and professional styling. We handle every detail so you walk in to a finished room.' },
  { name: 'Kitchen Renovation', slug: 'kitchen-renovation', price: 5000, priceType: 'FIXED' as const, duration: '3–6 weeks', featured: true, sortOrder: 3, shortDesc: 'Premium kitchen redesigns balancing function and avant-garde aesthetics.', description: 'From cabinetry design and material selection to appliance specification and tiling — our kitchen renovation service covers every detail. We work with certified tradespeople and premium suppliers to deliver kitchens that are as functional as they are beautiful.' },
  { name: 'Bathroom Renovation', slug: 'bathroom-renovation', price: 3500, priceType: 'FIXED' as const, duration: '2–4 weeks', featured: false, sortOrder: 4, shortDesc: 'Luxurious bathroom transformations with premium fixtures.', description: 'Transform your bathroom into a spa-like retreat. Our team manages tiling, fixtures, vanities, lighting, and accessories — all selected to create a cohesive, avant-garde aesthetic. Includes full project management.' },
  { name: 'Outdoor & Garden Design', slug: 'outdoor-garden-design', price: 1200, priceType: 'FIXED' as const, duration: '1–2 weeks', featured: false, sortOrder: 5, shortDesc: 'Transform your outdoor spaces into curated extensions of your interior.', description: 'We extend your interior design language to your outdoor spaces — terraces, gardens, rooftop decks, and balconies. Includes furniture selection, planting plans, lighting design, and styling.' },
  { name: 'Smart Home Installation', slug: 'smart-home-installation', price: 800, priceType: 'FIXED' as const, duration: '1–3 days', featured: false, sortOrder: 6, shortDesc: 'Intelligent lighting, climate, security and entertainment integration.', description: 'Our certified smart home specialists install and configure lighting, climate control, security cameras, motorised blinds, audio/visual systems, and whole-home automation. We work with Apple HomeKit, Google Home, and Amazon Alexa ecosystems.' },
  { name: 'Color & Material Consultation', slug: 'color-material-consultation', price: 90, priceType: 'HOURLY' as const, duration: '1–2 hours', featured: false, sortOrder: 7, shortDesc: 'Expert guidance on colour palettes, materials and finishes.', description: 'A focused session on colour and material decision-making. We bring physical samples, paint swatches, tile boards, and fabric samples to your home to help you visualise combinations in your specific light conditions.' },
  { name: 'Furniture Curation Service', slug: 'furniture-curation-service', price: 200, priceType: 'FIXED' as const, duration: '3–5 days', featured: false, sortOrder: 8, shortDesc: 'We select and source furniture to match your vision and budget.', description: 'Tell us your vision, budget, and space dimensions. Our design team creates a curated furniture proposal with sourcing from our collection and trusted suppliers worldwide, presented in a detailed mood board and specification document.' },
]

async function main() {
  console.log('🌱 Seeding Maison Avant-Garde database...')

  // Clear existing
  await db.productImage.deleteMany()
  await db.productVariant.deleteMany()
  await db.product.deleteMany()
  await db.category.deleteMany()
  await db.service.deleteMany()

  // Create categories
  const categoryMap: Record<string, string> = {}
  for (const cat of categories) {
    const created = await db.category.create({ data: cat })
    categoryMap[cat.slug] = created.id
  }
  console.log(`✅ Created ${categories.length} categories`)

  // Create products
  for (const p of products) {
    const { categorySlug, images, ...productData } = p
    const categoryId = categoryMap[categorySlug]
    if (!categoryId) { console.warn(`⚠️  Category not found: ${categorySlug}`); continue }

    await db.product.create({
      data: {
        ...productData,
        categoryId,
        images: {
          create: images.map((url, i) => ({ url, primary: i === 0, sortOrder: i, alt: productData.name })),
        },
      },
    })
  }
  console.log(`✅ Created ${products.length} products`)

  // Create services
  for (const s of services) {
    await db.service.create({ data: s })
  }
  console.log(`✅ Created ${services.length} services`)

  console.log('🎉 Seed complete!')
}

main()
  .catch((e) => { console.error(e); process.exit(1) })
  .finally(async () => { await db.$disconnect() })
